lab 9
dikareva-me/computer-graphics pull request #10
Opened 2024-04-12 21:31 UTC by dikareva-me

2024-04-15 09:17 UTC, Sairsey commented
Добрый день. У вас есть всё необходимое чтобы посчитать сколько времени экономит каждая техника которую вы прошли в рамках курса. Давайте найдем с вами то число кубов, при котором GPU Culling и Instancing имеют смысл. Для этого

1) Добавьте в IMGUI возможность переключать режим отрисовки кубиков. Первый - просто перебрать их в цикле и для каждого вызвать DrawIndexed. Второй - как в лабораторной 7. Третий - как в этой лабораторной.
2) Добавьте замер времени - сколько миллисекунд требуется на выполнение graphics->RenderFrame (при помощи std::chrono).
3) Запустите с разными параметрами и разным числом кубов например 10, 100, 1000, 10000, 100000.
4) Автоматизируйте сбор этих данных. Включайте каждую конфигурацию(Режим отрисовки и количество кубиков) отрисовки на 3 секунды. За эти 3 секунды найдите максимум, минимум и среднее. Эти значения сохраните в память и переходите к следующей конфигурации. После того как соберете данные - откройте файл и запишите в него эти данные в формате CSV. Важно открыть файл именно после замеров, т.к. открытие файла очень долгая операция.
От вас ожидается CSV с замерами и графики этих данных (можно Excel, можно matplotlib). Интересует зависимость времени от числа кубиков. В каждом графике должно быть не менее 100 точек(т.е. все замеры должны занять 15 минут) и должны быть видны точки "пересечения" режимов отрисовки.

2024-04-15 09:18 UTC, Sairsey requested changes
Я понимаю что задание непростое, поэтому сдвину дедлайн по нему до 19-ого числа

2024-04-15 09:18 UTC, Sairsey commented on Lab6/Lab6.sln
> +Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "Lab6", "Lab6.vcxproj", "{6B2EF87C-1A1D-4D9A-93CD-967B9FB188C5}"
А вы уверены что вам нужно менять этот файл?

2024-04-17 11:08 UTC, dikareva-me commented
![Figure_1](https://github.com/dikareva-me/computer-graphics/assets/91259546/97649841-1f16-4c17-b838-2d8adefb313a)
![Figure_2](https://github.com/dikareva-me/computer-graphics/assets/91259546/b2afc3d7-094f-4139-b526-22d4286d5f98)
![Figure_3](https://github.com/dikareva-me/computer-graphics/assets/91259546/233114c8-580d-45ae-86a2-9ad1f2e21a76)
![Figure_4](https://github.com/dikareva-me/computer-graphics/assets/91259546/80626ce3-55e3-4385-92db-cb6f162fb223)

2024-04-17 11:13 UTC, Sairsey commented
Принято!

2024-04-17 11:13 UTC, Sairsey approved these changes

2024-04-17 11:13 UTC, merged