lab 4
dikareva-me/computer-graphics pull request #5
Opened 2024-03-01 19:55 UTC by dikareva-me

Дикарева Мария

2024-03-02 17:00 UTC, Sairsey commented
Добрый вечер. Программа работает но есть несколько недочетов

2024-03-02 17:07 UTC, Sairsey requested changes

2024-03-02 17:07 UTC, Sairsey commented on lab/.vs/lab/v16/.suo
Удалите данный файл пожалуйста, он не требуется

2024-03-02 17:07 UTC, Sairsey commented on lab/lab/Debug/lab.vcxproj.FileListAbsolute.txt
Удалите данный файл пожалуйста, он не требуется

2024-03-02 17:07 UTC, Sairsey commented on lab/lab/Resource.h
> +// Включаемый файл, созданный в Microsoft Visual C++.
Уберите пожалуйста комментарии на русском языке

2024-03-02 17:07 UTC, Sairsey commented on lab/lab/lab.cpp
> +// Глобальные переменные:
У вас комментарии на русском языке и глобальные переменные используются. Не стоит так делать

2024-03-02 17:07 UTC, Sairsey commented on lab/lab.sln
Насколько я вижу, раньше вы делали лабораторные в папке WindowsProject1, и не создавали отдельные папки под каждую лабораторную. Почему вы решили эту делать в отдельной папке lab?
Я думаю вам стоит либо перенести код этой лабораторной в проект WindowsProject1, либо удалить WindowsProject1 как таковой

2024-03-02 17:10 UTC, Sairsey commented
И хотелось бы заметить что вот эти 2 кнопочки не работают. Почините их либо уберите совсем
![image](https://github.com/dikareva-me/computer-graphics/assets/19706253/e9158500-3834-4e80-b67b-7853b59f8b52)

2024-03-03 15:13 UTC, dikareva-me commented on lab/lab.sln
Поняла, удалила WindowsProject1

2024-03-03 18:12 UTC, Sairsey approved these changes
Задача зачтена =)

2024-03-03 18:12 UTC, merged