lab 5
dikareva-me/computer-graphics pull request #6
Opened 2024-03-17 19:21 UTC by dikareva-me

Дикарева Мария

2024-03-17 20:02 UTC, Sairsey reviewed
Добрый вечер. 
Как вы могли заметить, я не могу понять все причину некоторых ваших изменений. Как будто вы копировали с какой-то другой лабораторной...
Давайте вы попробуете ещё раз сами вчитаться в ваши изменения и возможно откатить странные правки. 
Ещё я заметил что ваши шейдеры уж сильно похожи на шейдеры ваших коллег... Поэтому вам то же задание что и им -  измените ваш код так, чтобы вы рисовали не полупрозрачные текстурированные объекты (об этом не было сказано в задании), а просто полупрозрачные объекты, цвет которых передается через constant buffer.
И так же предупреждаю, если я в следующий раз замечу похожие работы, я начну задавать более существенные вопросы по коду и по пониманию материала.

2024-03-17 20:02 UTC, Sairsey commented on lab/lab/Renderer.cpp
> +	DirectX::XMVECTOR objects;
Почему вы выбрали именно такое название для данной переменной

2024-03-17 20:02 UTC, Sairsey commented on lab/lab/Renderer.cpp
> +#define SafeRelease(A) if ((A) != NULL) { (A)->Release(); (A) = NULL; }
Почему вы заменили эту функцию на макрос?

2024-03-17 20:02 UTC, Sairsey commented on lab/lab/Skybox_VS.hlsl
> +cbuffer ViewBuffer : register (b0)
Зачем переименовывать названия буферов? И названия переменных?

2024-03-17 20:02 UTC, Sairsey requested changes
.

2024-03-18 15:34 UTC, dikareva-me commented on lab/lab/Renderer.cpp
> +#define SafeRelease(A) if ((A) != NULL) { (A)->Release(); (A) = NULL; }
Функция работала неправильно: при обнулении указателя (pointer=NULL) вне функции указатель не обнулялся. Проблема решилась прямым возвращением указателя из функции

2024-03-18 15:34 UTC, dikareva-me commented on lab/lab/Skybox_VS.hlsl
> +cbuffer ViewBuffer : register (b0)
Вернула названия

2024-03-18 15:35 UTC, dikareva-me commented on lab/lab/Renderer.cpp
> +	DirectX::XMVECTOR objects;
Поменяла

2024-03-18 16:56 UTC, Sairsey approved these changes
Лабораторная принята

2024-03-18 16:56 UTC, merged