Lab 7
dikareva-me/computer-graphics pull request #8
Opened 2024-03-29 19:52 UTC by dikareva-me

2024-04-01 08:44 UTC, Sairsey requested changes
Добрый день. К сожалению по текущему выводу не понять, работает ли корректно frustum culling или нет. Увеличьте число кубов как минимум до 1000 (а то у вас сфер больше чем кубов, зачем тогда instancing), и добавьте "отладочный режим" для frustum culling. "Отладочный режим" заключается в том, что вы фиксируете (эта операция обычно называется lock) посчитанные плоскости frustum-а, и перемещаете камеру без их обновления. Таким образом вы как-бы можете "посмотреть со стороны" на то, что происходит. Отдельным плюсом будет отрисовка линиями этих плоскостей( но это уже не обязательно).

2024-04-01 15:42 UTC, dikareva-me commented
На клавишу C добавлен отладочный режим

2024-04-01 17:59 UTC, Sairsey commented
Отлично, но у вас какие-то проблемы с skybox-ом 
![image](https://github.com/dikareva-me/computer-graphics/assets/19706253/d177ff67-5227-4fa8-8a54-8ad5bcc0275f)
И засчитывать лабораторную 8 (Postprocessing) вместе с этой я не буду, сделайте отдельный PR.

2024-04-01 17:59 UTC, Sairsey commented
Также, при изменении размера экрана у вас объекты деформируются. Исправьте это
![image](https://github.com/dikareva-me/computer-graphics/assets/19706253/a9926e5a-3418-4a26-82f8-a6c101b4a192)

2024-04-01 18:01 UTC, Sairsey requested changes
Если честно, я не хотел бы нажимать на кнопку "+" 1000 раз. Давайте добавим кнопку "+100" хотя бы

2024-04-01 18:01 UTC, Sairsey commented
Ну и исправьте warning-и.

2024-04-01 18:04 UTC, Sairsey commented
> Ну и исправьте warning-и.

В шейдерах тоже. Для этого нужно
```
	if (!SUCCEEDED(hr) && pErrMsg != nullptr)
	{
		OutputDebugStringA((const char*)pErrMsg->GetBufferPointer());
		return false;
	}
```
Заменить на два отдельных if-а.

2024-04-01 21:23 UTC, dikareva-me commented
Исправила все правки кроме деформации объектов. Не могли бы вы подсказать, пожалуйста, как исправить деформацию?

2024-04-01 21:27 UTC, Sairsey commented
> Исправила все правки кроме деформации объектов. Не могли бы вы подсказать, пожалуйста, как исправить деформацию? 

При обновлении размера окна, нужно пересчитывать матрицу проекции

2024-04-01 21:27 UTC, Sairsey requested changes
Нужно исправить деформации

2024-04-03 07:25 UTC, Sairsey approved these changes
Лабораторная 7  (Instancing) зачтена

2024-04-03 07:25 UTC, merged